services:

  blocklattice_mongo:
    image: mongo:latest
    container_name: blocklattice_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
       - 27017:27017
    volumes: #mongo:latest writes with root and removal is only possible root access
      - ./blocklattice_mongo:/data/db

  blocklattice_redis:
    image: redis:latest
    container_name: blocklattice_redis
    restart: unless-stopped
    ports:
      - 6379:6379
